package xyz.bhrnsw.mapper;

import java.util.List;
import xyz.bhrnsw.beans.Department;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Sun Mar 18 16:05:33 CST 2018
     */
    int deleteByPrimaryKey(String deptNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Sun Mar 18 16:05:33 CST 2018
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Sun Mar 18 16:05:33 CST 2018
     */
    Department selectByPrimaryKey(String deptNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Sun Mar 18 16:05:33 CST 2018
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table departments
     *
     * @mbg.generated Sun Mar 18 16:05:33 CST 2018
     */
    int updateByPrimaryKey(Department record);
}